---
- name: Fetch node token from master
  slurp:
    src: "/tmp/k3s-node-token"
  delegate_to: "{{ groups['masters'][0] }}"
  register: node_token

- name: Decode node token
  set_fact:
    node_token: "{{ node_token['content'] | b64decode }}"

- name: Install k3s worker
  shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['masters'][0]].ansible_host }}:6443 K3S_TOKEN={{ node_token }} sh -"
